development:
  port: 2223
  imagesDir: ./passportImages/
  selectors:
    - idhub
    - test
  managers:
    - 0x49dBa8f906c745B0a82f4D21E02BAFD7Df1a0be4
    - 0x7EbEE9a8A3530fd1e54017C39592A5a95af99d07
    - 0x00ba30197363845CDA7dFe38a4317b9Ac93e1BB2
    - 0x80b924655F091ea659dE16a3DF38825cF4D528E9
  mysql:
    username: "root"
    password: ""
    host: localhost
    port: 3306
    dbname: 2vid_test

production:
  port: 2223
  imagesDir: ./passportImages/
  selectors:
    - idhub
    - test
  managers:
    - idhub
    - test
  mysql:
    username: 
    password: 
    host: 
    port: 
    dbname:

environment: development